# (PART) I Anästhesie Bereiche {.unnumbered}

# AOP Ambulantes OP-Zentrum

Th. Müller

::: {.rmdnote}

The `bs4_book` style also includes an `.rmdnote` callout block like this one.

```{r collapse=TRUE} head(beaver1, n = 5) ```
:::

> ***`r fa("map-marker-alt")`*** Haus 51. über elbseitigen Aufzug H19

## Organisatorisches

|                         |       Nummer |
|-------------------------|-------------:|
| Bereichsleiter          |        19910 |
| OP-Saal 1 (Andok 55):   |         6915 |
| OP-Saal 2 (Andok 56):   |         6914 |
| OP-Saal 3 (Andok 57):   |         6913 |
| OP-Saal 4 (Andok 58):   |         6911 |
| ANE-Pflege:             | 19361/ 19362 |
| Aufenthaltsraum:        |         6975 |
| Tagesklinik (Sr. Gabi): |        18168 |
| Reinigung:              |        19341 |
| OP-Büro:                |         6966 |
| OP-Pflege:              |        16966 |

### Ausstattung

-   Narkosegerät Leon
-   C-Mac
-   Einmalbrochoskop 5 mm
-   Hotline
-   BZ-Gerät in Tagesklinik
-   BGA-Gerät
-   Ultraschall (GE-Laptop, Mindray Laptop, Philips Spark, Philips Afinity)
-   Relaxometer
-   Nervenstimulator
-   Baxter Pumpen
-   Rea-Rucksack
-   LifePak 20e

### Patientenströme

#### Normalstation

-   erster Patient kommt automatisch
-   Folgepatienten möglichst im Austausch mit AWR
-   AWR als Holdingarea nutzen.

#### MK3-S2 (diabetische Füße)

-   Die Patienten werden zuvor von der Station in die Tagesklinik (Sr. Gabi) gebracht.
-   post-OP ohne AWR wieder in die TK.
-   isolationspflichtige Patienten absprechen.

#### isolationspflichtige Patienten

-   direkt in den Saal, aus dem Saal direkt auf Station
-   Parallele Einleitung nur bei freiem Saal nach Absprache

#### ambulante Patienten

-   werden aus TK abgerufen

#### Kinder

-   Voraussetzungen: \>10 Jahre und \>30 kg

-   keine Risikokinder im AOP (z.B. Dysmorphie, schwieriger Atemweg, ITS-Pflichtigkeit, unkooperative Patienten, etc.) Risikopatienten

-   keine Risikopatienten im AOP, insbesondere:

    -   hohe Transfusionswahrscheinlichkeit (Logistik)
    -   OP mit wahrscheinlicher postoperativer ITS-/IMC-Pflichtigkeit
    -   bekannter schwieriger Atemweg nach Rücksprache

#### Patienten von ITS

-   Voraussetzung:

    -   stabiler Kreislauf
    -   keine schwerwiegende respiratorische Störung

## Auflegen

-   Schultertisch nur für Schulterchirurgie
-   bei Fuß-OP: Füße bis ans Ende des OP-Tisches
-   2 Armschienen
-   1 angeschraubter Infusionsständer

## Einleitung

-   OP-Tisch für RA nicht anbremsen
-   Patienten mit Name im Monitor aufnehmen: Scanner
-   niedrige Tropfengeschwindigkeit der Infusion
-   bei Standardeingriffen keine 3-Wege-Hähne oder Verlängerungen
-   Monitoring-Kabel sollen nicht den Boden berühren

## Anästhesie bei ambulanten Operationen

-   beachte allg. [Empfehlung DGAI](https://www.reanitrain.de/downloads/leitlinien/operative%20Eingriffe/ambulante%20OPs%20-%20zahnaerztliche%20Eingriffe/Leitlinie%20fuer%20ambulantes%20Operieren%20bzw.Tageschirurgie.pdf)

-   sparsam infundieren

-   Spinalanästhesie

    -   Chlorprocain, Prilocain 2% oder Bupivacain 0,5% ohne Fentanyl
    -   nach einer Spinalanästhesie: Ultraschall der Harnblase im AWR (Dokumentation nicht vergessen!)

-   Regionalanästhesie obere Extremität

    -   Bei zu erwartenden postoperativen Schmerzen Ropivacain sonst Prilocain

-   Regionalanästhesie untere Extremität

    -   Ropivacain nur nach Rücksprache
    -   Wundrandinfiltration durch den Operateur mit Ropivacain falls möglich

-   vor Entlassung: post-OP Visite durch Anästhesie (Tagesklinik)
