# AUG - Augenklinik

M. Trausch

> ***`r fa("map-marker-alt")`*** Haus 33. OP-Trakt ist in der 1. Etage. Der Zugang zur OP-Schleuse über Treppenhaus auf der Rückseite (Seite Fetscherstr.)

**`r fa("phone-square-alt")` Wichtige Telefonnummern**

+------------------------+--------------+
|                        | Nummer       |
+:=======================+=============:+
| Bereichsleiter         | 18048        |
+------------------------+--------------+
| ANE-Einleitung         | 2114         |
+------------------------+--------------+
| ANE-Pflege             | 11802        |
+------------------------+--------------+
| AUG-Aufwachraum        | 2687         |
+------------------------+--------------+
| AUG-S1                 | 13451 (3451) |
+------------------------+--------------+
| AUG-S4                 | 12352 (2352) |
+------------------------+--------------+
| Vorbereiter (AUG-Arzt) | 12114        |
+------------------------+--------------+

## Allgemeines-Augenklinik

### Besonderheiten

-   Stationäre Kinder kommen im Bett aus der Kinderklinik (Übergänge).
-   Ambulante Patienten Mittwoch und Donnerstag im Haus.

### Prämedikation

-   Augenklinik bestimmt i.d.R. KEINE Routinelaborwerte (bei Erfordernis „Bitte Labor!" vermerken).
-   Antihypertensiva (Dauermedikation) BEIBEHALTEN

### Anästhesieführung

-   postoperative Schmerztherapie mit peripheren Analgetika ausreichend
-   AWR: Montags kein Anspruch auf ANE-Pflegekraft für AWR
-   Besonderheiten Stationäre Kinder aus Kinderklinik
-   Ambulante Patienten Mi + Do im Haus

### Schmerztherapie

-   in der Regel sind periphere Analgetika für die postoperative Schmerztherapie ausreichend.

### Aufwachraum

-   Montags normalerweise keine Anästhesie-Pflegekraft für den AWR

## Eingriffe

### DMEK (Descement Mebrane Endothelial Keratoplasty)

-   Prämedikation: keine Besonderheiten
-   Anästhesieführung LM/ ITN
-   Zugänge/Monitoring Standard

### Enukleation

-   Beschreibung (kurz): Entfernung des Bulbus oculi\

-   Beschreibung (lang):

    -   Bei einer Enukleation wird der Bulbus oculi entfernt. Indikationen sind Tumoren (z.B. Retinoblastom, Melanom), Phthisis bulbi und gelegentlich direkte Traumafolgen. Bei der OP werden das hinter dem Auge befindliche Bindegewebe und die Augenmuskeln belassen. Der Augapfel wird meist durch eine Plombe ersetzt und an dieser die Augenmuskeln teilweise fixiert. So kann sich die später eingesetzte Augenprothese teilweise zum gesunden Auge mitbewegen.
    -   Bei einer Exenteration des Auges werden zusätzlich auch das Bindegewebe und die Augenmuskeln entfernt.

-   Prämedikation: keine Besonderheiten

-   Anästhesieführung: ITN

-   Zugänge/Monitoring: Standard

### Glaukom-OP

-   Beschreibung (lang):

    -   Zyklophotokoagulation (ZPK)

        -   Hier wird durch eine gezielte Laserbehandlung ein Teil des Ziliarkörpers vernarbt. Im Ziliarkörper wird das Kammerwasser produziert; durch eine teilweise Vernarbung erreicht man, dass weniger Kammerwasser produziert wird, und der Augendruck damit sinkt.
        -   Der Eingriff dauert nur wenige Minuten und kann in örtlicher Betäubung durchgeführt werden. Ggf. wird eine Allgemeinanästhesie mit Larynxmaske durchgeführt.

    -   Trabekelektomie (TE)

        -   Hier wird ein künstlicher Abflussweg für das Kammerwasser zu einer vorpräparierten Bindehauttasche geschaffen. Damit der neue Abfluss durch ablaufende Reparaturprozesse (Verwachsung, Narben) nicht wieder verschlossen wird, kommt Mitomycin C (MMC) zum Einsatz.
        -   Operationszeit ca. 40 min.

    -   Ahmed-Implantat

        -   Hier handelt es sich um ein Drainagesystem, das über eine Mikro-Schlauchverbindung Kammerwasser von der Vorderkammer des Auges zu einem unter die Bindehaut eingesetzten Implantat leitet, von wo das Kammerwasser über die Bindehaut resorbiert wird.
        -   Die Operationszeit beträgt ca. 45 min.

    -   Preserflo-Implantat

        -   Implantation eines Mikro-Schlauches, der Kammerwasser aus der Vorderkammer in eine vorpräparierte Bindehauttasche ableitet.

-   Beschreibung (kurz):

    -   ZPK, Zyklokryotherapie, TE, Ahmed-Implantat, InnFocus-(Preserflo-)Implantat

-   Prämedikation: Zyklophotokoagulation (ZPK) bitte auf orale PM verzichten

-   Anästhesieführung: LAMA, ITN

-   Zugänge/Monitoring: Standard

### Katarakt-OP

-   Beschreibung (lang):

    -   Bei der Kararakt-OP (bei uns umgangssprachlich mit "Phako" oder "Phako/HKL" bezeichnet) wird die getrübte Linse durch ein künstliches Linsenimplantat (siehe Abbildung) ersetzt. Der Eingriff erfolgt meist in Retrobulbäranästhesie. Falls eine Anästhesie erforderlich ist, wird meist eine Larynxmaske selten eine ITN durchgeführt.
    -   OP-Dauer bis ca. 10 min (bei schwierigen Verhältnissen bis 40 min).

-   Prämedikation: keine Besonderheiten

-   Anästhesieführung: LAMA, ITN

-   Zugänge/Monitoring: Standard

### Keratoplastik, perforierende ANE-Wiki

-   Prämedikation: keine Besonderheiten
-   Anästhesieführung: ITN
-   Zugänge/Monitoring: Standard
-   Besonderheit: 150 mg Prednisolon, 500 mg Acetazolamid

### Narkoseuntersuchung ANE-Wiki

-   Prämedikation: keine Besonderheiten
-   Anästhesieführung: LAMA, ITN
-   Zugänge/Monitoring: Standard

### PPV, kryo/limbusparallele Plombe ANE-Wiki

-   Prämedikation: keine Besonderheiten
-   Anästhesieführung: ITN
-   Zugänge/Monitoring: Standard

### Schiel-OP ANE-Wiki

-   Prämedikation: keine Besonderheiten
-   Anästhesieführung: LAMA, ITN
-   Zugänge/Monitoring: Standard
-   Besonderheiten: Glycopyrronium, Granisetron

### Tränenwegs-OP ANE-Wiki

-   Beschreibung:

    -   Kinder: Spülung u/o. Schlingenintubation;
    -   Erw.: oft als Dakryozystorhinostomie (DCR)

-   Prämedikation: keine Besonderheiten

-   Anästhesieführung: LM, DCR immer ITN

-   Zugänge/Monitoring: Standard

-   Besonderheiten: bei DCR Rachentamponade
